import { Manrope } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/Animations/LenisProvider";
import Footer from "@/components/Footer";
import BackgroundElements from "@/components/Animations/BackgroundElements";
import Navbar from "@/components/Navbar";



const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${manrope.variable} antialiased`}
      >

        <BackgroundElements/>
        <LenisProvider>
          <Navbar/>
        {children}
        <Footer/>
        </LenisProvider>
      </body>
    </html>
  );
}
